version: "3.8"
services:
  db:
    image: postgres:13.0
    container_name: breviary-db
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - 5433
    ports:
      - 5433:5432
    networks:
      - breviary
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    image: breviary-api
    container_name: breviary-api
    env_file: .env
    environment:
      PORT: 80
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - breviary

networks:
  breviary:
    driver: bridge

volumes:
  db-data:
