version: "3.8"
services:
  db:
    image: postgres:13.1
    container_name: breviary-db
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - breviary

  backend:
    image: breviary-backend
    container_name: breviary-backend
    env_file: .env
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
    networks:
      - breviary
    command:
      - ./gradlew
      - --no-daemon
      - --stacktrace
      - --info
      - :backend:test

networks:
  breviary:
    driver: bridge
