version: "3.8"
services:
  db:
    image: postgres:13.1
    container_name: breviary-db
    env_file: .env
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - breviary
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    image: breviary-backend
    container_name: breviary-backend
    env_file: .env
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db:5432/postgres
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - breviary

networks:
  breviary:
    driver: bridge

volumes:
  db-data:
