version: "3.8"
services:
  db:
    image: postgres:13.0
    container_name: breviary-db
    expose:
      - 5432
    networks:
      - breviary

  breviary-api:
    image: breviary-api
    container_name: breviary-api
    environment:
      PORT: 8081
    depends_on:
      - db
    networks:
      - breviary
    command:
      - ./gradlew
      - --no-daemon
      - --stacktrace
      - :backend:test

  breviary-model:
    image: breviary-model
    container_name: breviary-model
    command:
      - ./gradlew
      - --no-daemon
      - --stacktrace
      - :model:test

networks:
  breviary:
    driver: bridge
