version: "3.8"
services:
  db:
    environment:
      POSTGRES_PASSWORD: breviary-db-pass
  breviary-api:
    environment:
      VERSION: $GIT_HEAD
      GIT_BRANCH: $GIT_BRANCH
      AUTHOR: pipeline
      DB_USERNAME: postgres
      DB_PASSWORD: breviary-db-pass
      DB_URL: jdbc:postgresql://db:5432/postgres
      SPRING_PROFILES_ACTIVE: pipeline
