server.port: ${PORT:8081}
spring.data.rest.base-path: /api
springfox.documentation.swagger.v2.path: /v2/api-docs

spring.servlet.multipart:
  max-file-size: 250MB
  max-request-size: 250MB

# Enable response compression
server.compression:
  enabled: true
  mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,image/jpeg,image/png,image/gif
  min-response-size: 1024

server.error.whitelabel.enabled: false # Disable Whitelabel Error Page

#######################
# FLYWAY properties
#######################
spring.flyway:
  enabled: true
  baselineOnMigrate: true

#######################
# DB properties
#######################
spring.datasource:
  url: ${DB_URL:jdbc:postgresql://db:5432/postgres}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver-class-name: org.postgresql.Driver

spring.jpa:
  properties.hibernate.jdbc.lob.non_contextual_creation: true
  open-in-view: false
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect

spring:
  application:
    name: ${APPLICATION_NAME:breviary}
    email: ${APPLICATION_EMAIL:}
    allowedOrigins: ${ALLOWED_ORIGINS:}

management.endpoints.web.exposure.include: health
management.endpoint.health.show-details: when_authorized
