name: Check Pipeline

on:
  # manual dispatch
  workflow_dispatch:
  # run on PRs to master when - is opened,
  # new commit is pushed or is set as ready for review
  pull_request:
    types: [ opened, synchronize, ready_for_review ]
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    # disable run if the PR is draft (as our CLI creates PR as draft once the issue is in progress)
    if: github.event.pull_request.draft == false
    # enable postgres
    services:
      db:
        image: postgres:13.1
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.9

      - name: Prepare Links
        run: |
          ln -s $(pwd)/.env backend/src/main/resources/application.properties

      - name: Setup Environment Variables
        run: |
          echo "DB_USERNAME=postgres" >> $GITHUB_ENV
          echo "DB_PASSWORD=postgres" >> $GITHUB_ENV
          echo "DB_URL=jdbc:postgresql://db:5432/postgres?prepareThreshold=0" >> $GITHUB_ENV

      - name: Detekt Check
        run: |
          ./gradlew detekt

      - name: Assemble Code
        run: |
          ./gradlew assemble

      - name: Start Database
        run: |
          docker-compose -f docker-compose.pipeline.yml up -d db

      - name: Run Tests
        run: |
          ./gradlew test

      - name: Stop Database
        if: always()
        run: |
          docker-compose -f docker-compose.yml stop db
